var contry_code = {
    "DZ": "Algeria",
    "AS": "American Samoa",
    "AD": "Andorra",
    "AR": "Argentina",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BD": "Bangladesh",
    "BY": "Belarus",
    "BE": "Belgium",
    "BM": "Bermuda",
    "BR": "Brazil",
    "BG": "Bulgaria",
    "CA": "Canada",
    "CL": "Chile",
    "CO": "Colombia",
    "CR": "Costa Rica",
    "HR": "Croatia",
    "CZ": "Czechia",
    "DK": "Denmark",
    "DO": "Dominican Republic",
    "EE": "Estonia",
    "FO": "Faroe Islands",
    "FI": "Finland",
    "FR": "France",
    "GF": "French Guiana",
    "DE": "Germany",
    "GB": "Great Britain",
    "GL": "Greenland",
    "GP": "Guadeloupe (French)",
    "GU": "Guam (USA)",
    "GT": "Guatemala",
    "GG": "Guernsey",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "IE": "Ireland",
    "IM": "Isle of Man",
    "IT": "Italy",
    "JP": "Japan",
    "JE": "Jersey",
    "KR": "Korea-South",
    "LV": "Latvia",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MK": "Macedonia",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MT": "Malta",
    "MH": "Marshall Islands",
    "MQ": "Martinique (French)",
    "YT": "Mayotte",
    "MX": "Mexico",
    "FM": "Micronesia",
    "MD": "Moldova",
    "MC": "Monaco",
    "NL": "Netherlands",
    "NC": "New Caledonia (French)",
    "NZ": "New Zealand",
    "MP": "Northern Mariana Islands",
    "NO": "Norway",
    "PK": "Pakistan",
    "PW": "Palau",
    "PH": "Philippines",
    "PL": "Poland",
    "PT": "Portugal",
    "PR": "Puerto Rico",
    "RE": "Reunion (French)",
    "RO": "Romania",
    "RU": "Russia",
    "PM": "Saint Pierre and Miquelon",
    "SM": "San Marino",
    "RS": "Serbia",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "ZA": "South Africa",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SJ": "Svalbard and Jan Mayen Islands",
    "SE": "Sweden",
    "CH": "Switzerland",
    "TH": "Thailand",
    "TR": "Turkey",
    "US": "USA",
    "UA": "Ukraine",
    "UY": "Uruguay",
    "VA": "Vatican",
    "VI": "Virgin Islands (USA)",
    "WF": "Wallis and Futuna Islands"
}